---

- name: Rotate tower password from hashicorp vault
  hosts: localhost
  connection: local
  vars_prompt:
    -  name: token
       prompt: Enter token
       private: yes
  vars:
    org: demo
    secret: "{{ lookup('hashi_vault', 'secret=tower/root token={{ token }} url=http://127.0.0.1:8200') }}"
  tasks:

  - name: Add tower credential
    tower_credential:
      tower_verify_ssl: no
      name: root
      description: root password
      organization: "{{ org }}"
      username: root
      password: "{{ secret.password }}"
      state: present
      kind: ssh
